config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
    resources :likes , only: [:create , :destroy]
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:


    user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      elsif user.client?
        can :manage, Post, user_id: user.id
        can :manage, Comment, user_id: user.id
      else
        can :read ,Post
        can :read ,Comment
      end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
   end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts ,dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

   validates :content, presence: true , length: {minimum: 10}
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id ,uniqueness: {scope: :post_id}
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :category

  has_many :taggings, dependent: :destroy
  has_many :comments ,dependent: :destroy
  has_many :likes ,dependent: :destroy
  has_many :tags ,through: :taggings

  validates :body, presence: true , length: {minimum: 10}
  validates :title , presence: true


  def all_tags=(names)
    self.tags=names.split(',').map do |name|
      Tag.where(name: name).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(",")
  end


end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  # belongs_to :user
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :posts, through: :taggings
  has_many :taggings ,dependent: :destroy
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments ,dependent: :destroy
  has_many :posts ,dependent: :destroy
  has_many :likes ,dependent: :destroy

  after_create :assign_default_role

  def admin?
    has_role?(:admin)
  end

  def client?
    has_role?(:client)
  end

  private

  def assign_default_role
    self.add_role :client
  end
  # def all_tags=(names)
  #   self.tags=names.split(',').map do |name|
  #     Tag.where(name: name).first_or_create!
  #   end
  # end
  #
  # def all_tags
  #   tags.map(&:name).join(",")
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # rescue_from CanCan::AccessDenied do |exception|
  #   redirect_to '/', notice: exception.message
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_post
  before_action :set_comment ,only: [:show, :edit, :update, :destroy]

  def new
    @comment = @post.comments.new(comment_params)
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to @post , notice: 'Successfully commented'
    else
       redirect_to @post , alert: 'Blank comment'
    end
  end

  def show ;end

  def destroy
    if can? :destroy ,@comment
    # if @comment.user_id == current_user.id
      # || @post.user_id == current_user.id
      @comment.destroy
      redirect_to @post, alert: 'Comment Destroyed'
    else
      redirect_to @post
    end
  end

  def edit ;end
  def update
    if @comment.update(comment_params)
      redirect_to @post, notice: 'Comment Updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment=current_user.comments.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_post
  before_action :find_like, only: [:destroy]


  def create
    # if already_liked?
    #   flash[:notice] = "You can't like more than once"
    # else
       @post.likes.create(user_id: current_user.id)
    # end
    redirect_to post_path(@post)
  end
  def destroy
    # if !(already_liked?)
    #   flash[:notice] = "Cannot unlike"
    # else
       @like.destroy
    # end
    redirect_to post_path(@post)
  end


  private

  def like_params
    params.require(:like).permit(:post_id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
  end
  def find_like
    @like = @post.likes.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post , only: [:edit , :update,:show]
  def index
    @posts = Post.all
  end

  def show ;end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post Successfully Posted'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit;end

  def update
    if @post.update(post_params)
      redirect_to post_path , notice: "Post Successfully Updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = current_user.posts.find_by(id: params[:id])
    @post.destroy
    redirect_to posts_path,alert: 'Post Deleted'
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :category_id, :all_tags)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<% comments.each do |comment| %>
    <ul>
    <% if @post.user == current_user || comment.user == current_user %>
       <li><%= comment.content %> <%= link_to 'Edit', edit_post_comment_path(@post, comment) %>
       <%= link_to 'Destroy', post_comment_path(@post.id, comment.id), method: :delete, data: { confirm: 'Are you sure?'}  %></li>
    <% else %>
       <li> <%= comment.content %></li>
    <% end %>
    </ul>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [@post, @post.comments.build] do |form| %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h2>Editing Comment</h2>
<%= form_for([@post, @comment]) do |f| %>
<div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

<%= link_to 'Show', @post %>

app/views/layouts/_errorsHandling.html.erb
<% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_flashmessage.html.erb
<% if flash[:notice] %>
      <div class="alert alert-success" ><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>

        <div class="alert alert-secondary" ><%= flash[:alert] %></div>
  <% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Forum</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
            </ul>
            <form class="d-flex">
                <% if user_signed_in? %>
                <button class="btn btn-outline-success" type="submit"><%= link_to "Logout", destroy_user_session_path, method: :delete %></button>
                <% else %>
                <button class="btn btn-outline-success" type="submit"><%= link_to "Sign Up", new_user_registration_path %></button>
                <button class="btn btn-outline-success" type="submit"><%= link_to "Sign In", new_user_session_path %></button>
                <% end %>

            </form>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForumA</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <%= render'layouts/flashmessage' %>

  <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
    <%= render 'layouts/errorsHandling',post: @post %>
    <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>
  <div class="field">
      <%= form.label :all_tags %>
      <%= form.text_field :all_tags %>
    </div>

  <div class="field">
      <%= form.label :category_id %>
      <%= form.collection_select :category_id, Category.all, :id, :category %>
   </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path%>

app/views/posts/index.html.erb
<div class="container mt-3">
  <h2>Posts</h2>
  <p>Show all Posts</p>
   <table class="table">
    <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Category</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <% @posts.each do |post| %>
      <tr>
          <td><%= post.title %></td>
          <td><%= post.body %></td>
          <td><%= post.category.category %></td>


          <td><button type="button" class="btn btn-info"><%= link_to "Show", post_path(post) %></button></td>
          <% if can? :update , post%>
            <td><button type="button" class="btn btn-info"><%= link_to "Edit", edit_post_path(post) %></button></td>
          <% end %>
          <% if can? :delete , post %>
          <td><button type="button" class="btn btn-info"><%= link_to "Delete", post, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
          <% end %>
          </tr>
    <% end %>
    </tr>
    </tbody>
  </table>
  <% if user_signed_in? %>
    <%= link_to "New Post", new_post_path %>
  <% else %>

  <% end %>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form', post: @post %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @post.title %>
</p>
<p>
   <strong>Body:</strong>
   <%= @post.body %>
</p>


<!-- -->
<p>
   <strong>Category:</strong>
   <%=@post.category.category%>
</p>



<p>
   <strong>Tags:</strong>
   <% @post.tags.each do |u| %>
   <%=  u.name %>
   <% end %>
</p>


<% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
<%= @post.likes.count%>
<% if pre_like %>
  <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
<% else %>
  <%= button_to 'Like', post_likes_path(@post), method: :post %>
<% end %>



<p>
   <strong>Comment:</strong>
   <%= render "comments/comment", comments: @post.comments%>
   <%= render "comments/form" %>
</p>



<% if can? :update, @post %>
    <%= link_to 'Edit', edit_post_path(@post) %>
<% else %>
    <%= link_to 'Back', posts_path %>
<%end %>